language: node_js
node_js:
  - 6.10.2
env:
  - CXX=g++-4.8
addons:
  sauce_connect:
    username: princu7
  jwt:
    secure: mytdk9Wu6KI8EAdrjmhanlXWAnPfVaWZ0g0Ay00WdeUW/U/fkfyV532h6fGByNyjs5xZulRnS5Ri5BhZpBahlp2vGYWd6novmk4uuedurPDJ8utgPd3jaMJv/fPYPn55iy7R40y5XTnHBXCCrzyqYgrDJ7Lw0doTOAYEV/4UGH6V3lTPQGaq+11sg+8bSJs18iUKdJ21Phi5M8IxlqxINdJnRoxV0r3SoEXf9DTWtJGO/EUvccsXfdwiq5vkdK2Ue4gYsDTXaTy/qwxHWYnjL4T9ePIhplqUK8gb5/MmTrzsCyJXwiCxl+t7k4fUa1dyYiuzh7QaufedZnVYXoVrr6mIAZ/1qIjFo138B4DKJxMtfdwoBz9cBCd+XE9oxrjnRI7w1oDlWIuni54W95ngjzwC5gC3Y7rudsq0HHnW599f9iQLk8oDmqPWHONLrw5h9jTiPzVspNHza62sdxWLsX4sSQrpVu159PhogaZDH8frloNyZuc2KaPU6Ln+rGBfW49nRB7yKT3NaT24q2NOcQmm8M0/4NUYqF3Ap9evaPeNt+klKRECnIe+W6Z9AgKd7gNsZdDEF8IFFBcd2RdPh7CwPcjMqwck4kOwIu/KMEMfqebQ7w7fOSmiZ8LJdckdwGnHrQHIHBhubycZ0muwvOacLRI516Sdmb4W42t8xBw=
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: 46f6d31d6b0777711b6c7e733234b023bda56e2e02c792c68c889005cf032ea6
install:
  - npm install -g istanbul mocha
  - npm install
script:
  - istanbul cover _mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash cli.sh
  - bash sample_cli.sh
  - bash gh_deploy.sh
deploy:
  provider: heroku
  api_key:
    secure: ogAnS9LCFXVkMocd7DbYup45n8eRHIFpeptDP947PajNy27xPfOspBGj1UMQri/0d/hAYqdC52Bfd7eccyOLm/6H9d5LzDWNBHz4rqT+FXkdpJf7PofC7kUua5oUXlh0eiccBKwn3j8n3suLnLsigJ/UD4rjKIGKrfodAud4XhsPdg0+XVNihDa6rSMH5G6TTAYQjukCLT2TlCPFiyNSJvfjH1+h2uE93vWBzsjkLzlWMoAr00uAwlYJgotoQ9v2ECqfZ7mhAJCwSoRdqmir9Xvj5GSj3qRc953bbye8ZJoEMXDt9N2GNwV3/3XFtrc/fQuq7cRj2OFZuDZ/Ch0Z2MQGbXoG0gqRfntoGFBDcx4w+rifburPnIDS4V4H5DpW/lohGG6tWLSa4ynfF5utnUowpy9pT8RCBmrvZkLfSfqF4J/rh7HzfyhMpDGqv5hcs+RSJZQiLN8sdcSRvz2aKoaAxXi7U0IfUAUluJ9fPD5WRmUbV3FwAxEjjuRMKYabelam7lvKI6vyf6lWt1oyI4EKd7M33JfeRbcJ9BwM4SDbgxHCSeSI4AIiqFs1l35ZVfDlz8yLhHt33ZWSBrWoGw3e83rUJPc/I9Uxu4xX3WKCZ+tXKD8YA64rdeoCDra/2Ad2Rm4doFgdWmW2I23jKNx/CtKiq3YXcWmiBCaL6IQ=
  app: opev-webgen-dev
  on:
    repo: fossasia/open-event-webapp
    branch:
      - master
      - development
