language: node_js
node_js:
  - 6.10.2
sudo: required
services:
  - docker
env:
  - CXX=g++-4.8 PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
addons:
  sauce_connect:
    username: princu7
  jwt:
    secure: nF1dJjAQVch/Er3uguMqF7XtOOnEFf06xIPzs3G6Co+62M7WbUVA0paTFtMF/n/vfeTSf+eQ9H5noeicVvVt0SMrQFKQLAg6hohqWqx0Z1urWAx1kHz2Zj0qtlS3sgCz5wOiWQ9zn7x2V4inkrY0nCPB09JQf9b5kIF+IK5Yqe5B6iWOn1ivHEdNKQavbKPjGV57yn63Y0/uSGBaBT6zyftA2ouLS+dtXmb0uLxAAT/MsfwUwo9v7Ijt5Cs8me0T7IgXJ+u3+KThELGLcHli0G6X9TMnNAx5HVoAGcteRYUgI+CvahrSe4Ab1LpxvVar6Bk8K/Rl+Ho++vJ69hxP+1PPVDnPYt3k7QWTQl7uAOZfnLaiuEHToC7Mxn4VBIJ//ZxWe5PHBRcIdD0XhZFh2CNyT/HsjKSlb5yhOlSCCmOdLw47z5vB0TEH7d+Sa8Pg9xNjWH3WUrrwTMXnO6wJABQ8ztSW9e8IFMegYWZ6QFRAic2mrzk8za+jNKy2Rvjv8fzxGaNhk0TtvruIFfus6sJ84wpdo0cWU+NOVB/rnfm1g62bCQjgJsQrcX0Hehwib+6E+6Snd9vz2zlRSiRg0rmTXRoh152rBlHvkdq0qFPWQsFOZc6C7hd5ild0PIbX6oMbwFnvPbbKPG+71NNAYxLb2D27umZPCnxR/fAWJcE=
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
    repo_token: 46f6d31d6b0777711b6c7e733234b023bda56e2e02c792c68c889005cf032ea6
install:
  - npm install -g istanbul mocha
  - npm install
script:
  - istanbul cover _mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash cli.sh
  - bash sample_cli.sh
  - bash gh_deploy.sh
  - bash kubernetes/travis/deploy.sh
deploy:
  provider: heroku
  api_key:
    secure: ogAnS9LCFXVkMocd7DbYup45n8eRHIFpeptDP947PajNy27xPfOspBGj1UMQri/0d/hAYqdC52Bfd7eccyOLm/6H9d5LzDWNBHz4rqT+FXkdpJf7PofC7kUua5oUXlh0eiccBKwn3j8n3suLnLsigJ/UD4rjKIGKrfodAud4XhsPdg0+XVNihDa6rSMH5G6TTAYQjukCLT2TlCPFiyNSJvfjH1+h2uE93vWBzsjkLzlWMoAr00uAwlYJgotoQ9v2ECqfZ7mhAJCwSoRdqmir9Xvj5GSj3qRc953bbye8ZJoEMXDt9N2GNwV3/3XFtrc/fQuq7cRj2OFZuDZ/Ch0Z2MQGbXoG0gqRfntoGFBDcx4w+rifburPnIDS4V4H5DpW/lohGG6tWLSa4ynfF5utnUowpy9pT8RCBmrvZkLfSfqF4J/rh7HzfyhMpDGqv5hcs+RSJZQiLN8sdcSRvz2aKoaAxXi7U0IfUAUluJ9fPD5WRmUbV3FwAxEjjuRMKYabelam7lvKI6vyf6lWt1oyI4EKd7M33JfeRbcJ9BwM4SDbgxHCSeSI4AIiqFs1l35ZVfDlz8yLhHt33ZWSBrWoGw3e83rUJPc/I9Uxu4xX3WKCZ+tXKD8YA64rdeoCDra/2Ad2Rm4doFgdWmW2I23jKNx/CtKiq3YXcWmiBCaL6IQ=
  app: opev-webgen-dev
  on:
    repo: fossasia/open-event-webapp
    branch:
      - master
      - development
